### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by roedelk** [roedelk/SEBC#1]

**Comment by roedelk** [comment]
Agreement on
- AWS region: EU (Frankfurt)
- Availability Zone: eu-central-1b

**Comment by roedelk** [comment]
Instances created, addresses noted

**Comment by roedelk** [comment]
Swappiness adapted.

**Comment by roedelk** [comment]
System Configuration Checks completed.

**Comment by roedelk** [comment]
Mysql installed, working on replication

**Comment by roedelk** [comment]
Replication not working due to missing connection between Mysql server :-(

**Comment by roedelk** [comment]
Stopping work on Ubuntu, restart on Redhat 6

**Comment by mfernest** [comment]
Let's stay in contact today in case you come across similar issues. It's instructive to start over one time but I'd like to help you avoid doing that a second time.
